### PR TITLE
Handle missing arduinos a bit better

### PR DESCRIPTION
**Pull request by stevendpclark**
Hey Bradley,

Here's my first attempt at helping out on the C# side of things for the program. I've added the following "features" to the program.
- Automatically attempt to connect to every Arduino until we successfully connect on startup to one of them. If the config file specifies a com port and it exists, it will be pre-selected, and attempted first, else we fallback on the auto detection...
- This takes care of the multiple NO, message boxes showing up.
- Re-implement missing save the port button (GitHub didn't have your version?)
- Introduce separate status labels for Arduino and iRacing SDK at the bottom of the window
- Revert the Arduino code back to the non "hot" version ;)

First time I push changes into GitHub for a Visual Studio app, I didn't update the binaries, let me know if this causes any difficulties for you to import into your version or if something isn't working after this import on your side.

### CODE REVIEW

**Review by Brad0404 — CHANGES_REQUESTED** [review]
Hi Steven, I have included the up to date code to the main branch...if you want to include your changes to that I can then give it a bit of a test.
Cheers
Brad

**Comment by stevendpclark** [comment]
Sure, I'll have a look tonight

**Comment by stevendpclark** [comment]
Hey Brad, 

Have a look at the pull request now. I've merged in your changes and tweaked mine. Let me know how things look on your end and if you approve of my changes. 

Cheers,
-Steven

**Comment by Brad0404** [comment]
Everything seemed to work OK...had a quick test and no issues I can see.  Thanks for the changes.

**Pull request merged**
